/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistaCalculadora;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author USER
 */
public class FrmCalculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmCalculadora.class.getName());

    public JButton getBtn1() {
        return btn1;
    }
    public JButton getBtn2() {
        return btn2;
    }
    public JButton getBtn3() {
        return btn3;
    }
    public JButton getBtn4() {
        return btn4;
    }
    public JButton getBtn5() {
        return btn5;
    }
    public JButton getBtn6() {
        return btn6;
    }
    public JButton getBtn7() {
        return btn7;
    }
    public JButton getBtn8() {
        return btn8;
    }
    public JButton getBtn9() {
        return btn9;
    }
    public JButton getBtnAC() {
        return btnAC;
    }
    public JButton getBtnBorrar() {
        return btnBorrar;
    }
    public JButton getBtnCE() {
        return btnCE;
    }
    public JButton getBtnCambiarSigno() {
        return btnCambiarSigno;
    }
    public JButton getBtnCero() {
        return btnCero;
    }
    public JButton getBtnDivision() {
        return btnDivision;
    }
    public JButton getBtnIgual() {
        return btnIgual;
    }
    public JButton getBtnMul() {
        return btnMul;
    }
    public JButton getBtnPunto() {
        return btnPunto;
    }
    public JButton getBtnRestar() {
        return btnRestar;
    }
    public JButton getBtnSumar() {
        return btnSumar;
    }
    public JLabel getLblOperacion() {
        return lblOperacion;
    }
    public JLabel getLblPantalla() {
        return lblPantalla;
    }
    /**
     * Creates new form FrmCalculadora
     */
    public FrmCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAC = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnRestar = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnSumar = new javax.swing.JButton();
        btnCambiarSigno = new javax.swing.JButton();
        btnCero = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnMul = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblPantalla = new javax.swing.JLabel();
        lblOperacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jPanel1.setLayout(new java.awt.GridLayout(5, 4, 5, 5));

        btnAC.setBackground(new java.awt.Color(255, 51, 51));
        btnAC.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnAC.setText("AC");
        jPanel1.add(btnAC);

        btnCE.setBackground(new java.awt.Color(255, 153, 51));
        btnCE.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnCE.setText("CE");
        jPanel1.add(btnCE);

        btnBorrar.setBackground(new java.awt.Color(255, 153, 51));
        btnBorrar.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnBorrar.setText("<");
        jPanel1.add(btnBorrar);

        btnIgual.setBackground(new java.awt.Color(51, 153, 255));
        btnIgual.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnIgual.setText("=");
        jPanel1.add(btnIgual);

        btn7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btn7.setText("7");
        jPanel1.add(btn7);

        btn8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btn8.setText("8");
        jPanel1.add(btn8);

        btn9.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btn9.setText("9");
        jPanel1.add(btn9);

        btnDivision.setBackground(new java.awt.Color(51, 204, 255));
        btnDivision.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnDivision.setText("/");
        jPanel1.add(btnDivision);

        btn4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btn4.setText("4");
        jPanel1.add(btn4);

        btn5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btn5.setText("5");
        jPanel1.add(btn5);

        btn6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btn6.setText("6");
        jPanel1.add(btn6);

        btnRestar.setBackground(new java.awt.Color(51, 204, 255));
        btnRestar.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnRestar.setText("-");
        jPanel1.add(btnRestar);

        btn1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btn1.setText("1");
        jPanel1.add(btn1);

        btn2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btn2.setText("2");
        jPanel1.add(btn2);

        btn3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btn3.setText("3");
        jPanel1.add(btn3);

        btnSumar.setBackground(new java.awt.Color(51, 204, 255));
        btnSumar.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnSumar.setText("+");
        jPanel1.add(btnSumar);

        btnCambiarSigno.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnCambiarSigno.setText("+/-");
        jPanel1.add(btnCambiarSigno);

        btnCero.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnCero.setText("0");
        jPanel1.add(btnCero);

        btnPunto.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnPunto.setText(".");
        jPanel1.add(btnPunto);

        btnMul.setBackground(new java.awt.Color(51, 204, 255));
        btnMul.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        btnMul.setText("x");
        jPanel1.add(btnMul);

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        lblPantalla.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblPantalla.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        lblOperacion.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblOperacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOperacion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCalculadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAC;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCambiarSigno;
    private javax.swing.JButton btnCero;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnMul;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnRestar;
    private javax.swing.JButton btnSumar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblOperacion;
    private javax.swing.JLabel lblPantalla;
    // End of variables declaration//GEN-END:variables
}